// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dfbAjn6TM0jDW2IfAbUhqfEYxhTdZ_U',
    appId: '1:857109791419:web:37949084bea9d396301f9e',
    messagingSenderId: '857109791419',
    projectId: 'ebookme-3b8bc',
    authDomain: 'ebookme-3b8bc.firebaseapp.com',
    storageBucket: 'ebookme-3b8bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvsaJT9qbVO3J6EYewFbxckyoacoWhyRA',
    appId: '1:857109791419:android:4b1aff36a84ac100301f9e',
    messagingSenderId: '857109791419',
    projectId: 'ebookme-3b8bc',
    storageBucket: 'ebookme-3b8bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJR3HjQfW3JDohAVu3deVIr39ALlW4EvA',
    appId: '1:857109791419:ios:3e698fe870fe5900301f9e',
    messagingSenderId: '857109791419',
    projectId: 'ebookme-3b8bc',
    storageBucket: 'ebookme-3b8bc.firebasestorage.app',
    iosClientId: '857109791419-gth5cs04u28unt5g8q7uhfmsgve4516u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookhotel',
  );

}