// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDekop9EHRxhj0Z9mYHjMJuD95DucB_Jgs',
    appId: '1:77635846971:web:a17455f04d6719434a2d1e',
    messagingSenderId: '77635846971',
    projectId: 'bookmebackend',
    authDomain: 'bookmebackend.firebaseapp.com',
    storageBucket: 'bookmebackend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe_cDQ-IIjf-M-mO7XHH2VFoUAJONGyrw',
    appId: '1:77635846971:android:dd8c72ad8bc16af64a2d1e',
    messagingSenderId: '77635846971',
    projectId: 'bookmebackend',
    storageBucket: 'bookmebackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPSZWtgeCJ7YovsNySge0uGmDkCzCeVUQ',
    appId: '1:77635846971:ios:5d0aa2054ca69b7c4a2d1e',
    messagingSenderId: '77635846971',
    projectId: 'bookmebackend',
    storageBucket: 'bookmebackend.firebasestorage.app',
    androidClientId: '77635846971-srj7i41dv6s66c3gjt9tm1jbv3p6t6f0.apps.googleusercontent.com',
    iosClientId: '77635846971-j2fm5gvtdkn6kfbq9e85oecpbafthc0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookhotel',
  );

}