// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksHo-C8FWDm1wtENXWwBhzvm16CFbGPg',
    appId: '1:240141652886:web:da471dbda7b061252283b7',
    messagingSenderId: '240141652886',
    projectId: 'bookhotel-c5c98',
    authDomain: 'bookhotel-c5c98.firebaseapp.com',
    storageBucket: 'bookhotel-c5c98.firebasestorage.app',
    measurementId: 'G-L1BBML9XBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOhBGxFp-LWJfC2drQZtrKM28rBEK_Bs',
    appId: '1:240141652886:android:3bb270fb55d6d3aa2283b7',
    messagingSenderId: '240141652886',
    projectId: 'bookhotel-c5c98',
    storageBucket: 'bookhotel-c5c98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ljc1I5_1of-_f0oaw3ywAT--qvhWPlw',
    appId: '1:240141652886:ios:78d7d55de1fa9cab2283b7',
    messagingSenderId: '240141652886',
    projectId: 'bookhotel-c5c98',
    storageBucket: 'bookhotel-c5c98.firebasestorage.app',
    iosClientId: '240141652886-lhvf06h0s6csk86o88m7hgml665pmel9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookhotel',
  );

}